name: cv-project

on:
  push:
    branches: [ "masterV" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update files to s3
        run: ls
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: us-east-1
        #run: aws s3 cp /path/to/source s3://${{ secrets.BUCKET_NAME }}/ --recursive