name: cv-project

on:
    workflow_dispatch:

jobs:
  update_bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: us-east-1
      - name: Sync files to s3
        run: |
            aws s3 sync . s3://${{ secrets.BUCKET_NAME }} --delete --exclude "*" --include "index.html" --include "style.css" --include "style.css"
      
      - name: Invalidate Caches from AWS Cloudfront Distribution
        id: invalidate_caches
        uses: snakierboss52/invalidate-cloudfront-action@v0.1.0
        with:
          cloudfront-distribution-id: ${{ secrets.DISTRIBUTION }}
          cloudfront-invalidation-path: '/*'
      #- name: Invalidate CloudFront
      #  uses: chetan/invalidate-cloudfront-action@v2
      #  env:
      #      DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
      #      PATHS: "/*"
      #      AWS_REGION: "us-east-1"
      #      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      #      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

  #security-owasp-scan:
  #  needs: [update_bucket]
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: ZAP Scan
  #      uses: zaproxy/action-full-scan@v0.9.0
  #      with:
  #        target: ${{ secrets.URL_SERVER }}